DROP TABLE SALUDOS.ROLESXUSUARIO
DROP TABLE SALUDOS.FUNCIONALIDADESXROL
DROP TABLE SALUDOS.ROLES
DROP TABLE SALUDOS.FUNCIONALIDADES
DROP TABLE SALUDOS.CLIENTES
DROP TABLE SALUDOS.EMPRESAS
DROP TABLE SALUDOS.TRANSACCIONES
DROP TABLE SALUDOS.CALIFICACIONES
DROP TABLE SALUDOS.ITEMS
DROP TABLE SALUDOS.FACTURAS
DROP TABLE SALUDOS.PUBLICACIONES
DROP TABLE SALUDOS.VISIBILIDADES
DROP TABLE SALUDOS.RUBROS
DROP TABLE SALUDOS.USUARIOS

DROP TABLE SALUDOS.FECHA
DROP FUNCTION SALUDOS.fechaActual
DROP PROCEDURE SALUDOS.crearTablaFecha

DROP PROCEDURE SALUDOS.generarUsuariosDeClientes
DROP PROCEDURE SALUDOS.generarUsuariosDeEmpresas
DROP PROCEDURE SALUDOS.migrarUsuarios
DROP SCHEMA SALUDOS