DROP TABLE SALUDOS.PUBLICACIONES
DROP TABLE SALUDOS.VISIBILIDADES
DROP TABLE SALUDOS.RUBROS
DROP TABLE SALUDOS.TRANSACCIONES
DROP TABLE SALUDOS.CALIFICACIONES
DROP TABLE SALUDOS.EMPRESAS
DROP SCHEMA SALUDOS